In [2]:
# Import Library

In [4]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [5]:
# Load the dataset

In [6]:
df = pd.read_csv('Customer_Data.csv')

In [8]:
# Top 5 Rows of Data

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
# Last 5 Rows of Data

In [11]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [12]:
# Information of the Data(Customer)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [14]:
# Check the summary statictics of all the column

In [15]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [18]:
# df.describe() default only numerical column statitics.if we want all column statitics summary then do df.describe(include = 'all')

In [19]:
# Check the missing values

In [20]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [29]:
"""There is null value in Review Rating column. We can replace by Median value but in the Customer Data it's not the best. Because rating can varies a lot 
depending on the category. Clothing Category can have different review rating than footwear category. Now, if we just take the overall median and fill it 
everywhere, we are basically forcing cothing items to get the same review ratings as footwear item. And that can introduce bias into our dataset. Instead,
what we will do is impute the missing values using the median review rating within each category. That's way if a clothing item is missing its review 
rating, it's get replaced with the median review rating of a clothing item, not the footwear item."""

"There is null value in Review Rating column. We can replace by Median value but in the Customer Data it's not the best. Because rating can varies a lot \ndepending on the category. Clothing Category can have different review rating than footwear category. Now, if we just take the overall median and fill it \neverywhere, we are basically forcing cothing items to get the same review ratings as footwear item. And that can introduce bias into our dataset. Instead,\nwhat we will do is impute the missing values using the median review rating within each category. That's way if a clothing item is missing its review \nrating, it's get replaced with the median review rating of a clothing item, not the footwear item."

In [35]:
# This code fills missing values in the 'Review Rating' column using the median rating of each category

In [34]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [43]:
# Check the result

In [32]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [36]:
#Data Cleaning in the right way because it is not bias.

In [40]:
""" Convert all names into snake cast : Naming Convention in programming where spaces between words are replaced with an underscore(_) and all the 
letters are typically in lowercase. Make them more readable"""

' Convert all names into snake cast : Naming Convention in programming where spaces between words are replaced with an underscore(_) and all the \nletters are typically in lowercase. Make them more readable'

In [49]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [50]:
# Check all updated columns 
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [53]:
# Create a new columns age_group 
labels  = ['Young Adult' , 'Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

In [56]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle Aged
1   19  Young Adult
2   50  Middle Aged
3   21  Young Adult
4   45  Middle Aged
5   46  Middle Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle Aged

In [59]:
# Create  column purchase_frequency_days

frquency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Anually' : 365,
    'Every 3 Months' : 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frquency_mapping)

In [63]:
# Check the column of purchase_frequency_days
df[['purchase_frequency_days'  , 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                      NaN               Annually
9                     90.0              Quarterly

In [66]:
""" The 'promo_code_used' column indicates whether a promotional code was applied during the purchase. If a promo code is used, a discount is 
 automatically reflected in the 'discount_applied' column. However, if a discount is applied without the use of a promo code, it likely represents other
types of discounts such as seasonal offers, automatic price reductions, or promotional campaigns. So in discount_applied its always true.
"""

" The 'promo_code_used' column indicates whether a promotional code was applied during the purchase. If a promo code is used, a discount is \n automatically reflected in the 'discount_applied' column. However, if a discount is applied without the use of a promo code, it likely represents other\ntypes of discounts such as seasonal offers, automatic price reductions, or promotional campaigns. So in discount_applied its always true.\n"

In [69]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [76]:
df = df.drop('promo_code_used', axis=1)

In [78]:
#Result Columns Name
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [73]:
pip install pyodbc sqlalchemy

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: sqlalchemy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl (70 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
# Connecting the jupyter Notebook to Microsoft SQl For Data Transmission

In [79]:
from sqlalchemy import create_engine

# Step 1.1: Connection details
server = "SHIVAM-KUMAR-MA\SQLEXPRESS"   
database = "customer_behavior"

# Step 1.2: Create engine (Windows Authentication)
engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# Step 1.3: Load DataFrame
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data successfully loaded!")

<>:4: SyntaxWarning: invalid escape sequence '\S'
<>:4: SyntaxWarning: invalid escape sequence '\S'
C:\Users\hp\AppData\Local\Temp\ipykernel_24868\709181747.py:4: SyntaxWarning: invalid escape sequence '\S'
  server = "SHIVAM-KUMAR-MA\SQLEXPRESS"

Data successfully loaded!